-ifndef(__ASPIKE_PORT_RETURN_CODES_HRL__).
-define(__ASPIKE_PORT_RETURN_CODES_HRL__, 1).

-define(AEROSPIKE_OK, 0).
-define(AEROSPIKE_ERR_CLIENT, -1).
-define(AEROSPIKE_ERR_RECORD_NOT_FOUND, 2).
-define(AEROSPIKE_ERR_TIMEOUT, 9).
-define(AEROSPIKE_NO_RESPONSE, 15).

-endif.
